version: "3"
services:
  mongo:
    # Instead of build tag we're using image tag because we're using the official image of MongoDB.
    # This will pull the official image from the Docker hub.

    # Specifying name so that the server will have the correct URI
    container_name: mongodb_mern-boilerplate
    # If you are developing on a specific Mongo version, you may specify it here.
    image: mongo:latest
    ports:
      - "27017:27017"
    # This option overrides the default app network, so that you can create a more complex network later if needed.
    networks:
      - mern-boilerplate
    volumes:
      - mongo-data:/data/db
  server:
    # Specify the location of our Makefile
    build: ./server/
    ports:
      # Mapping the exposed port, i.e. 3001 to our VM port 3001 so that we can test the application on our port 3001
      - "3001:3001"
      # This option overrides the default app network, so that you can create a more complex network later if needed.
    networks:
      - mern-boilerplate
    volumes:
      - ./server:/usr/src/app
      - ./usr/src/app/node_modules
    # Ensures the server does not start before our Mongo service is running
    depends_on:
      - mongo
  client:
    # Specify the location of our Makefile
    build: ./client/
    # Mapping the eposed port, i.e. 3000, to our VM port 3000. 
    ports:
      - "3000:3000"
    # This option overrides the default app network, so that you can create a more complex network later if needed.
    networks:
      - mern-boilerplate
    # Mapping the exposed port, i.e. 3000 to our VM port 3000 so that we can test the application on our port 3000
    volumes: 
      - ./client:/usr/src/app
      - ./usr/src/app/node_modules
    # Ensures the client does not start before our server is running
    depends_on:
      - server
  
networks: 
  mern-boilerplate:
    driver: bridge

volumes:
  mongo-data:
    driver: local